import type { Startup } from "./types";

const updatedAt = "2026-07-17T12:00:00.000Z";
const make = (startup: Omit<Startup, "updatedAt" | "source">): Startup => ({
  ...startup,
  updatedAt,
  source: { name: `${startup.name} official website`, url: startup.website, verified: true }
});

export const seedStartups: Startup[] = [
  make({ id:"openai", name:"OpenAI", tagline:"AI research and products", description:"Research and product company building general-purpose artificial intelligence systems and tools.", sector:"Artificial intelligence", stage:"Scaleup", location:"San Francisco, US", founded:2015, website:"https://openai.com", founders:["Sam Altman","Greg Brockman"], team:"1,000+", score:96, signals:["Broad product platform","Strong enterprise positioning"] }),
  make({ id:"anthropic", name:"Anthropic", tagline:"Reliable and steerable AI systems", description:"AI safety and research company developing language models and enterprise AI products.", sector:"Artificial intelligence", stage:"Growth", location:"San Francisco, US", founded:2021, website:"https://anthropic.com", founders:["Dario Amodei","Daniela Amodei"], team:"500–1,000", score:93, signals:["Safety-led differentiation","Research-intensive team"] }),
  make({ id:"stripe", name:"Stripe", tagline:"Financial infrastructure for the internet", description:"Payments and financial infrastructure platform for internet businesses.", sector:"Fintech", stage:"Scaleup", location:"San Francisco, US", founded:2010, website:"https://stripe.com", founders:["Patrick Collison","John Collison"], team:"5,000+", score:94, signals:["Developer-led distribution","Deep infrastructure expansion"] }),
  make({ id:"mistral", name:"Mistral AI", tagline:"Frontier AI built in Europe", description:"Paris-based company focused on efficient foundation models and developer tools.", sector:"Artificial intelligence", stage:"Growth", location:"Paris, France", founded:2023, website:"https://mistral.ai", founders:["Arthur Mensch","Guillaume Lample","Timothée Lacroix"], team:"100–250", score:88, signals:["Efficient model strategy","European market positioning"] }),
  make({ id:"ramp", name:"Ramp", tagline:"The financial platform for modern business", description:"Financial operations platform combining cards, spend controls, procurement and automation.", sector:"Fintech", stage:"Growth", location:"New York, US", founded:2019, website:"https://ramp.com", founders:["Eric Glyman","Karim Atiyeh"], team:"1,000+", score:89, signals:["Spend control wedge","Repeatable finance buyer"] }),
  make({ id:"vercel", name:"Vercel", tagline:"The frontend cloud", description:"Developer cloud platform for building, deploying and scaling modern web applications.", sector:"Developer tools", stage:"Scaleup", location:"San Francisco, US", founded:2015, website:"https://vercel.com", founders:["Guillermo Rauch"], team:"500–1,000", score:87, signals:["Framework-hosting flywheel","AI application tailwind"] }),
  make({ id:"linear", name:"Linear", tagline:"Tools for high-performance product teams", description:"Product development platform focused on issue tracking, planning and collaboration.", sector:"SaaS", stage:"Growth", location:"San Francisco, US", founded:2019, website:"https://linear.app", founders:["Karri Saarinen","Jani Eväkallio","Tuomas Artman"], team:"50–100", score:85, signals:["Opinionated workflow","Bottom-up adoption"] }),
  make({ id:"supabase", name:"Supabase", tagline:"The open-source Firebase alternative", description:"Developer platform providing hosted Postgres, authentication, storage and edge functions.", sector:"Developer tools", stage:"Growth", location:"Singapore", founded:2020, website:"https://supabase.com", founders:["Paul Copplestone","Ant Wilson"], team:"100–250", score:84, signals:["Open-source distribution","Database-led expansion"] }),
  make({ id:"synthesia", name:"Synthesia", tagline:"AI video for business", description:"Video creation platform using synthetic presenters and AI production tools.", sector:"Artificial intelligence", stage:"Scaleup", location:"London, UK", founded:2017, website:"https://synthesia.io", founders:["Victor Riparbelli","Steffen Tjerrild"], team:"500–1,000", score:80, signals:["Enterprise workflow focus","Localization advantage"] }),
  make({ id:"pleo", name:"Pleo", tagline:"Smart spending for growing businesses", description:"European spend-management platform for cards, expenses, invoices and controls.", sector:"Fintech", stage:"Scaleup", location:"Copenhagen, Denmark", founded:2015, website:"https://pleo.io", founders:["Jeppe Rindom","Niccolo Perra"], team:"500–1,000", score:77, signals:["Expense-management wedge","European localization"] }),
  make({ id:"toogoodtogo", name:"Too Good To Go", tagline:"Good food should not go to waste", description:"Marketplace connecting consumers with surplus food from restaurants and shops.", sector:"Climate & consumer", stage:"Scaleup", location:"Copenhagen, Denmark", founded:2015, website:"https://toogoodtogo.com", founders:["Mette Lykke"], team:"1,000+", score:78, signals:["Local network effects","Habit-linked impact"] }),
  make({ id:"helsing", name:"Helsing", tagline:"AI for defence and national security", description:"European defence technology company applying software and AI to decision support and autonomy.", sector:"Defence technology", stage:"Growth", location:"Munich, Germany", founded:2021, website:"https://helsing.ai", founders:["Gundbert Scherf","Torbjørn Sjögren"], team:"250–500", score:82, signals:["Sovereign capability demand","Engineering-intensive model"] })
];
