import { useEffect, useMemo, useState } from "react";
import type { Startup } from "../shared/types";

type View="overview"|"library"|"compare"|"sources";
const initials=(name:string)=>name.split(" ").map(x=>x[0]).join("").slice(0,2);

export default function App(){
  const [startups,setStartups]=useState<Startup[]>([]), [view,setView]=useState<View>("overview"), [query,setQuery]=useState(""), [sector,setSector]=useState("all"), [stage,setStage]=useState("all"), [selected,setSelected]=useState<Startup|null>(null), [compare,setCompare]=useState<string[]>([]), [message,setMessage]=useState("");
  const load=()=>fetch("/api/startups").then(r=>r.json()).then(r=>setStartups(r.data)).catch(()=>setMessage("API unavailable — run npm run dev"));
  useEffect(()=>{ void load(); },[]);
  const sectors=useMemo(()=>[...new Set(startups.map(x=>x.sector))].sort(),[startups]);
  const filtered=startups.filter(x=>(!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))&&(sector==="all"||x.sector===sector)&&(stage==="all"||x.stage===stage));
  const compared=compare.map(id=>startups.find(x=>x.id===id)).filter(Boolean) as Startup[];
  const toggle=(id:string)=>setCompare(current=>current.includes(id)?current.filter(x=>x!==id):current.length<3?[...current,id]:current);
  const refresh=async()=>{const r=await fetch("/api/refresh",{method:"POST"});const body=await r.json();setMessage(body.message||"Refresh complete");load();};

  return <div className="shell"><aside><div className="brand"><i>V</i><b>venture atlas</b></div><small>WORKSPACE</small>{(["overview","library","compare","sources"] as View[]).map(v=><button className={view===v?"active":""} onClick={()=>setView(v)} key={v}><span>{v==="overview"?"◇":v==="library"?"▤":v==="compare"?"◫":"◎"}</span>{v}{v==="library"&&<em>{startups.length}</em>}{v==="compare"&&compare.length>0&&<em>{compare.length}</em>}</button>)}<div className="side-bottom"><span className="dot"/>Source-aware data<p>{startups.length} verified links</p></div></aside><main><header><span>Research workspace / <b>{view}</b></span><button onClick={refresh}>↻ Refresh</button></header><section>
  {message&&<div className="notice" onClick={()=>setMessage("")}>{message}<span>×</span></div>}
  {view==="overview"&&<><div className="hero"><div><label>PRIVATE MARKET INTELLIGENCE</label><h1>See the landscape<br/><em>more clearly.</em></h1><p>A living library of ambitious companies, market signals, and the patterns behind them.</p></div><button onClick={()=>setView("library")}>Explore library →</button></div><div className="stats"><Stat label="Startups indexed" value={startups.length}/><Stat label="Sectors covered" value={sectors.length}/><Stat label="Source links" value={startups.length}/><Stat label="Average score" value={startups.length?Math.round(startups.reduce((a,b)=>a+b.score,0)/startups.length):0}/></div><div className="grid"><div className="panel"><Title over="MOMENTUM RADAR" title="The names to watch"/><div className="ranked">{startups.slice(0,6).map((x,i)=><button onClick={()=>setSelected(x)} key={x.id}><small>0{i+1}</small><Logo x={x}/><span><b>{x.name}</b><i>{x.sector} · {x.location.split(", ").at(-1)}</i></span><strong>{x.score}</strong>→</button>)}</div></div><div className="panel"><Title over="COVERAGE" title="Where the signal is"/><div className="bars">{sectors.slice(0,7).map(s=>{const n=startups.filter(x=>x.sector===s).length;return <div key={s}><span>{s}<b>{n}</b></span><i><u style={{width:`${20+n*18}%`}}/></i></div>})}</div></div></div></>}
  {view==="library"&&<><PageTitle over="THE LIBRARY" title="Companies, in context." text="Search across profiles, sectors, stages and operating signals."/><div className="toolbar"><input placeholder="Search companies, founders, markets…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All sectors</option>{sectors.map(x=><option key={x}>{x}</option>)}</select><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{["Seed","Series A","Series B","Growth","Scaleup"].map(x=><option key={x}>{x}</option>)}</select></div><div className="table"><div className="tr head"><span></span><span>Company</span><span>Focus</span><span>Stage</span><span>Location</span><span>Score</span></div>{filtered.map(x=><div className="tr" key={x.id}><button className={compare.includes(x.id)?"check checked":"check"} onClick={()=>toggle(x.id)}>{compare.includes(x.id)?"✓":""}</button><button className="company" onClick={()=>setSelected(x)}><Logo x={x}/><span><b>{x.name}</b><small>{x.tagline}</small></span></button><span>{x.sector}</span><i>{x.stage}</i><span>{x.location}</span><strong>{x.score}</strong></div>)}</div></>}
  {view==="compare"&&<><PageTitle over="DECISION SUPPORT" title="Compare the shape of a bet." text="Choose up to three companies for side-by-side context."/><div className="chips">{startups.map(x=><button className={compare.includes(x.id)?"chosen":""} onClick={()=>toggle(x.id)} key={x.id}><Logo x={x}/>{x.name}</button>)}</div>{compared.length?<div className="compare">{compared.map(x=><div className="card" key={x.id}><button className="x" onClick={()=>toggle(x.id)}>×</button><Logo x={x}/><h2>{x.name}</h2><p>{x.tagline}</p><strong className="big">{x.score}<small>Atlas score</small></strong>{[["Stage",x.stage],["Sector",x.sector],["Founded",x.founded],["Team",x.team],["Evidence","1 verified source"]].map(([a,b])=><div className="row" key={String(a)}><span>{a}</span><b>{b}</b></div>)}<button className="profile" onClick={()=>setSelected(x)}>View full profile →</button></div>)}</div>:<div className="empty">Select companies above to build a comparison.</div>}</>}
  {view==="sources"&&<><PageTitle over="DATA FOUNDATION" title="Know where the signal comes from." text="Refresh a configured JSON feed or import normalized records."/><div className="source panel"><div><span className="dot"/><b>Official company websites</b><small>{startups.length} records</small></div><strong>Verified</strong></div><div className="contract"><b>Live feed contract</b><p>Set <code>STARTUP_DATA_URL</code> to an endpoint returning <code>Startup[]</code> or <code>{`{ startups: Startup[] }`}</code>. Records are upserted and remain searchable.</p><button onClick={refresh}>Refresh pipeline</button></div></>}
  </section></main>{selected&&<div className="backdrop" onClick={()=>setSelected(null)}><article className="drawer" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><Logo x={selected}/><h2>{selected.name}</h2><p className="tag">{selected.tagline}</p><div className="score"><strong>{selected.score}</strong><span>Atlas score<br/><small>Operating context + source coverage</small></span></div><a href={selected.website} target="_blank">Visit website ↗</a><h3>THESIS</h3><p>{selected.description}</p><h3>AT A GLANCE</h3><div className="facts"><span>Sector<b>{selected.sector}</b></span><span>Stage<b>{selected.stage}</b></span><span>Location<b>{selected.location}</b></span><span>Team<b>{selected.team}</b></span></div><h3>FOUNDERS</h3><div className="founders">{selected.founders.map(x=><i key={x}>{x}</i>)}</div><h3>SIGNALS</h3>{selected.signals.map(x=><div className="signal" key={x}>✦ <span>{x}</span></div>)}</article></div>}</div>;
}
function Logo({x}:{x:Startup}){return <i className="logo">{initials(x.name)}</i>}
function Stat({label,value}:{label:string,value:number}){return <div><span>◇</span><small>{label}</small><b>{value}</b><i>Current workspace</i></div>}
function Title({over,title}:{over:string,title:string}){return <div className="title"><small>{over}</small><h2>{title}</h2></div>}
function PageTitle({over,title,text}:{over:string,title:string,text:string}){return <div className="page-title"><label>{over}</label><h1>{title}</h1><p>{text}</p></div>}
